import { Provider } from "@/components/ui/provider";

import {Header} from "@/components/layout/header";

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Fontes
const geistSans = localFont({
  src: "../assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Head
export const metadata: Metadata = {
  title: "Arthur A.",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} flex flex-col items-center antialiased`}>
        <Provider>

          <Header />

          {children}

        </Provider>
      </body>
    </html>
  );
}
